#config/application.yml
global:
    # 'multi' mode 
    #    Used for script <command> style scripts (such as git) with multiple 
    #    commands. Commands are defined in the 'lib/commands/' folder.
    #
    # 'single' mode
    #    For traditional  normal scripts. Please note that single mode commands
    #    will ignore all commands in the command folder.
    mode: multi
    script_name: taxomatic
    hidden_dir_name: .taxomatic
    default_command: help
    description: displays a sample receipt for a shopping cart with specific taxation rules
